// ─────────────────────────────────────────────────────────────────────────────
// LITTER DETAIL — Kull C, Kennel Granheim
// Universe: Astor × Saga · 5 valper · uke 4 · 7 søknader
// ─────────────────────────────────────────────────────────────────────────────

const litterKennel = {
  name: "Kennel Granheim",
  prefix: "av Granheim",
  owners: "Ole og Marit",
};

const litter = {
  id: "kull-c",
  letter: "C",
  callName: "Kull C",
  poetic: "«Stars of the Fjord»",
  sire: { id: "astor", name: "Astor av Granheim", titles: "NUCH NORDUCH", health: "HD A · ED 0 · Øyne klar · DM N/N", tone: "sire" },
  dam:  { id: "saga",  name: "Saga vom Nordwald", titles: "NUCH", health: "HD A · ED 0 · Øyne klar 2025 · DM N/N", tone: "dam" },
  mating:   "14. februar 2026",
  whelping: "14. april 2026",
  delivery: "8. juni 2026",
  weekOfAge: 4,
  status: "active",        // planned | mated | pregnant | whelped | rearing(active) | delivery | done
  count: { total: 5, males: 3, females: 2 },
  available: 2,
  applicationsTotal: 7,
};

// ── Stages ──────────────────────────────────────────────────────────────────
const litterStages = [
  { id: "planned",  label: "Planlagt",    short: "Plan" },
  { id: "mated",    label: "Paret",       short: "Paret" },
  { id: "pregnant", label: "Drektig",     short: "Drektig" },
  { id: "whelped",  label: "Valping",     short: "Født" },
  { id: "rearing",  label: "Oppfostring", short: "Oppfostring" },
  { id: "delivery", label: "Levering",    short: "Levering" },
  { id: "done",     label: "Avsluttet",   short: "Avsluttet" },
];

// ── 5 puppies (full demographics) ───────────────────────────────────────────
const puppies = [
  {
    id: "birk",
    color: "red",
    colorLabel: "Rød",
    sex: "m",
    name: "Birk",
    status: "reservert",
    statusLabel: "RESERVERT",
    weight: 3.1,
    trend: "up",
    delta: "+90 g",
    notes: "Energisk, ledende i kullet. Liker mat.",
    assignedTo: "Familien Hansen, Bergen",
    tone: "sire",
  },
  {
    id: "loke",
    color: "blue",
    colorLabel: "Blå",
    sex: "m",
    name: "Loke",
    status: "tilgjengelig",
    statusLabel: "TILGJENGELIG",
    weight: 3.3,
    trend: "up",
    delta: "+95 g",
    notes: "Største i kullet. Rolig på dag, aktiv på kveld.",
    tone: "sire",
  },
  {
    id: "ulf",
    color: "green",
    colorLabel: "Grønn",
    sex: "m",
    name: "Ulf",
    status: "beholdt",
    statusLabel: "BEHOLDT",
    weight: 3.0,
    trend: "up",
    delta: "+85 g",
    notes: "Vurdert som potensiell avlshann. Sterk pels, rolig sinn.",
    assignedTo: "Beholdt av oppdretter",
    tone: "sire",
  },
  {
    id: "mira",
    color: "purple",
    colorLabel: "Lilla",
    sex: "f",
    name: "Mira",
    status: "tilgjengelig",
    statusLabel: "TILGJENGELIG",
    weight: 2.7,
    trend: "up",
    delta: "+70 g",
    notes: "Mest tilbakeholden av tispene. God på sosialisering.",
    tone: "dam",
  },
  {
    id: "idun",
    color: "yellow",
    colorLabel: "Gul",
    sex: "f",
    name: "Idun",
    status: "tilbudt",
    statusLabel: "TILBUDT",
    weight: 2.6,
    trend: "up",
    delta: "+70 g",
    notes: "Liten, men spiser bra. Tilbudt — venter på svar.",
    assignedTo: "Familien Berg, Stavanger (venter)",
    tone: "dam",
  },
];

// ── 7 applications ──────────────────────────────────────────────────────────
const applications = [
  {
    id: "pettersen",
    who: "Familien Pettersen",
    city: "Trondheim",
    status: "ny",
    statusLabel: "NY",
    received: "for 4 timer siden",
    summary: "Familie i Trondheim — utstillingshund-ambisjoner, har erfaring fra annen rase.",
    intent: "Utstilling · familie",
    household: "Familie · 2 voksne · 2 barn (12, 14)",
    housing: "Enebolig med stor hage",
    experience: "Hatt golden retriever 2009–2021. Ingen tidligere elghund.",
    why: "Vi har fulgt Astor på utstilling i to år. Vi vil prøve å bygge en utstillingshund med en linje med god type og temperament.",
    activity: "Aktive · tur, ski, utstilling",
    references: "Veterinær: Smedbakken, Trondheim",
    match: [
      { k: "Erfaring med hund", state: "ok" },
      { k: "Tilstrekkelig plass", state: "ok" },
      { k: "Førstegangs-eier av rasen", state: "warn" },
    ],
    messages: [],
    avatarTone: "warm",
  },
  {
    id: "aas",
    who: "Familien Aas",
    city: "Tromsø",
    status: "ny",
    statusLabel: "NY",
    received: "for 1 dag siden",
    summary: "Familie i Tromsø, brukshund-erfaring fra Border Collie.",
    intent: "Familie · tur",
    household: "Familie · 2 voksne · 3 barn (4, 7, 10)",
    housing: "Enebolig med inngjerdet uteareal",
    experience: "Border collie 2014–2024, fokus på lydighet og frittsøk.",
    why: "Vi flytter til Lyngenfjord til sommeren. Vi ønsker en rolig hund som tåler norsk vintersport og lange turer.",
    activity: "Veldig aktive · ski, klatring, tur",
    references: "Veterinær: Polarklinikken, Tromsø",
    match: [
      { k: "Erfaring med hund", state: "ok" },
      { k: "Tilstrekkelig plass", state: "ok" },
      { k: "Aktivitetsnivå passer rasen", state: "ok" },
    ],
    messages: [],
    avatarTone: "info",
  },
  {
    id: "berg",
    who: "Familien Berg",
    city: "Stavanger",
    status: "tilbudt",
    statusLabel: "TILBUDT VALP",
    received: "for 2 uker siden",
    summary: "Par i 50-årene, jakter aktivt elg. Tilbudt Idun (gul tispevalp).",
    intent: "Jaktkamerat",
    household: "Par · 2 voksne, ingen barn",
    housing: "Småbruk på Jæren, 12 mål inngjerdet",
    experience: "3 elghunder før — siste (Tora) gikk bort 2024.",
    why: "Vi savner en jaktkamerat. Skal jakte elg sammen, og hunden skal bo sammen med oss inne.",
    activity: "Aktive · jakt, tur",
    references: "Veterinær: Jæren Dyreklinikk · oppdretter: Kennel Lia",
    match: [
      { k: "Erfaring med rasen", state: "ok" },
      { k: "Tilstrekkelig plass", state: "ok" },
      { k: "Jakt-erfaring", state: "ok" },
    ],
    avatarTone: "ok",
    offered: { puppyId: "idun", whenOffered: "23. apr 2026", expires: "30. apr 2026" },
    messages: [
      { from: "applicant", t: "Hei Marit! Vi har lest om Astor lenge. Vi mistet Tora i fjor og kjenner at vi er klare. Saga ser ut som en flott mor.", at: "10. apr · 14:22" },
      { from: "breeder",   t: "Hei dere — så fint å høre fra dere igjen. Vi husker Tora godt, hun var en av Vidars beste døtre. Send oss noen bilder fra Jæren, så snakkes vi.", at: "10. apr · 19:05" },
      { from: "applicant", t: "Her er gården — vi har gjerdet hele jordet. Vi har plass og tid. Kan vi besøke når valpene er 6 uker?", at: "11. apr · 09:30", attachment: { kind: "image", label: "FARM PHOTO" } },
      { from: "breeder",   t: "Vakkert. Kom 26. mai — da er valpene 6 uker og klare for en god lang prat. Vi har en gul tispevalp som ser ut som hun matcher dere — Idun. Rolig, fokus, kommer fra Sagas siste kull-stil.", at: "11. apr · 11:14" },
      { from: "applicant", t: "Tusen takk. Vi gleder oss veldig.", at: "11. apr · 12:00" },
    ],
  },
  {
    id: "olsen",
    who: "Marit Olsen",
    city: "Oslo",
    status: "samtale",
    statusLabel: "I SAMTALE",
    received: "for 5 dager siden",
    summary: "Singel i 30-årene, første hund. Har lest seg opp på rasen i to år.",
    intent: "Familie · tur",
    household: "Singel · 1 voksen, jobber hjemmefra",
    housing: "Rekkehus med liten hage, mye marka rett utenfor",
    experience: "Førstegangs-eier. Har vært dagmamma for venner sin elghund.",
    why: "Jeg vil ha en hund som matcher meg — rolig, selvstendig, men med vilje. Jeg jobber hjemmefra og kan ha hunden tett på.",
    activity: "Aktive · ski, tur, klatring",
    references: "Veterinær: Vinderen Dyreklinikk",
    match: [
      { k: "Tilstrekkelig plass", state: "ok" },
      { k: "Aktivitetsnivå", state: "ok" },
      { k: "Førstegangs-eier av rasen", state: "warn" },
    ],
    avatarTone: "warm",
    messages: [
      { from: "applicant", t: "Hei. Jeg leste at dere kanskje vurderer enkelt-personer som førstegangs-eiere av rasen. Jeg har dagmammet en elghund i Oslo i to år.", at: "13. apr · 21:10" },
      { from: "breeder",   t: "Hei Marit — det stemmer, men vi vurderer hver søknad. Fortell mer om hvem du har dagmammet og hvor mye tid du faktisk har.", at: "14. apr · 08:15" },
      { from: "applicant", t: "Hunden heter Bjørk, eier av Lise Solberg på Holmenkollen — referanse er ok. Jeg jobber 4 dager i uka hjemmefra, og er sjelden borte mer enn 4 timer.", at: "14. apr · 12:42" },
    ],
  },
  {
    id: "hansen",
    who: "Familien Hansen",
    city: "Bergen",
    status: "godkjent",
    statusLabel: "GODKJENT",
    received: "for 3 uker siden",
    summary: "Familie med 2 barn, har hatt elghund før. Birk er reservert hos dem.",
    intent: "Familie · tur · jakt",
    household: "Familie · 2 voksne · 2 barn (8, 10)",
    housing: "Enebolig i Bergen, hytte på fjellet",
    experience: "Elghund 2011–2023 (Tjalve, eid av samme familie)",
    why: "Vår forrige elghund Tjalve var familiemedlem og jaktkamerat i 12 år. Vi vil ha en hund med samme grunnholdning.",
    activity: "Aktive · tur, jakt, ski",
    references: "Veterinær: Bjørgvin Dyreklinikk · oppdretter: Kennel Bjørke",
    match: [
      { k: "Erfaring med rasen", state: "ok" },
      { k: "Tilstrekkelig plass", state: "ok" },
      { k: "Familie passer rasen", state: "ok" },
    ],
    avatarTone: "ok",
    offered: { puppyId: "birk", whenOffered: "26. mar 2026", accepted: true, deposit: true },
    messages: [],
  },
  {
    id: "nilsen",
    who: "Tor Nilsen",
    city: "Hamar",
    status: "samtale",
    statusLabel: "I SAMTALE",
    received: "for 8 dager siden",
    summary: "Jeger, 45 år, søker en arbeidshund med god nese.",
    intent: "Jakt · sport",
    household: "Par · 2 voksne",
    housing: "Småbruk i Hedmark, 6 mål",
    experience: "2 elghunder, siste var Vidars sønn (Brage)",
    why: "Jeg har drevet jakt i 20 år og ønsker en ung hund å bygge linje på.",
    activity: "Veldig aktive · jakt, sporhund-prøver",
    references: "Veterinær: Hamar Dyreklinikk · jakt-makker: Per Berg",
    match: [
      { k: "Erfaring med rasen", state: "ok" },
      { k: "Jakt-erfaring", state: "ok" },
      { k: "Familie-passende hund", state: "warn" },
    ],
    avatarTone: "info",
    messages: [
      { from: "applicant", t: "Hei. Jeg ringer fra Hedmark. Tør jeg spørre om Loke (blå hannvalp) er ledig?", at: "10. apr · 19:33" },
      { from: "breeder",   t: "Hei Tor — han er ledig, men vi har flere søkere på ham. Send inn søknad, så snakkes vi rolig.", at: "11. apr · 07:48" },
    ],
  },
  {
    id: "lund",
    who: "Karina Lund",
    city: "Kristiansand",
    status: "avvist",
    statusLabel: "AVVIST",
    received: "for 12 dager siden",
    summary: "Førstegangs-eier i leilighet uten utearea. Avvist høflig.",
    intent: "Familie",
    household: "Singel · 1 voksen",
    housing: "Leilighet i sentrum, ingen utearea",
    experience: "Førstegangs-eier",
    why: "Jeg har alltid ønsket meg hund.",
    activity: "Stillesittende",
    references: "—",
    match: [
      { k: "Bolig passer rasen", state: "err" },
      { k: "Aktivitetsnivå", state: "err" },
    ],
    avatarTone: "muted",
    messages: [],
  },
];

// ── Daily log ──────────────────────────────────────────────────────────────
const dailyLog = [
  { d: "27. apr 2026", week: 4, day: 13, summary: "Alle veier mer enn 2,8 kg. Loke er den største (3,3 kg). ENS dag 5 fullført.", thumb: "puppies" },
  { d: "26. apr 2026", week: 4, day: 12, summary: "Første solid-food forsøk — soaked kibble. Mira spiste mest.", thumb: "food" },
  { d: "25. apr 2026", week: 4, day: 11, summary: "Eyes fully open. Hørselen er på vei. Idun reagerte på navn første gang.", thumb: "eyes" },
];

const breederTemplates = [
  "Hva slags fysisk aktivitet ser dere for dere hver dag?",
  "Hvem skal være primær-omsorgsperson for hunden?",
  "Hvordan tenker dere å håndtere ferier de første 12 årene?",
  "Hvor mye tid kan hunden være alene i løpet av en uke?",
  "Hvilke erfaringer har dere med valpe-trening?",
];

// ── Form steps for application ─────────────────────────────────────────────
const applicationSteps = [
  { id: "who",        label: "Hvem er dere?",                short: "Hvem" },
  { id: "everyday",   label: "Hverdagen deres",              short: "Hverdag" },
  { id: "experience", label: "Erfaring og forventninger",    short: "Erfaring" },
  { id: "refs",       label: "Referanser og bekreftelse",    short: "Refs" },
];

Object.assign(window, {
  litterKennel, litter, litterStages, puppies, applications,
  dailyLog, breederTemplates, applicationSteps,
});
